import esbuild from "esbuild";
import process from "process";
import builtins from "module";

const banner = `/*
Publish to Google Docs - Obsidian Plugin
THIS IS A GENERATED/BUNDLED FILE. Do not edit directly.
*/
`;

const prod = process.argv[2] === "production";

esbuild.build({
    banner: { js: banner },
    entryPoints: ["src/main.ts"],
    bundle: true,
    external: [
        "obsidian",
        "electron",
        "@codemirror/autocomplete",
        "@codemirror/collab",
        "@codemirror/commands",
        "@codemirror/language",
        "@codemirror/lint",
        "@codemirror/search",
        "@codemirror/state",
        "@codemirror/view",
        "@lezer/common",
        "@lezer/highlight",
        "@lezer/lr",
        ...builtins.builtinModules,
    ],
    format: "cjs",
    target: "es2018",
    logLevel: "info",
    sourcemap: prod ? false : "inline",
    treeShaking: true,
    outfile: "main.js",
    minify: prod,
}).catch(() => process.exit(1));
